name: demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - openpyxl
  - pandas
  - ipykernel
  - SQLAlchemy
  - ipython-sql
  - pip
  - black
  - flake8
  - pip:
    - duckdb
    - duckdb-engine
